"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var RawComponent_js_1 = require("./core/RawComponent.js");
// Document metadata
exports.$link = RawComponent_js_1.rawComponent('link');
exports.$style = RawComponent_js_1.rawComponent('style');
// Content sectioning
exports.$address = RawComponent_js_1.rawComponent('address');
exports.$article = RawComponent_js_1.rawComponent('article');
exports.$aside = RawComponent_js_1.rawComponent('aside');
exports.$footer = RawComponent_js_1.rawComponent('footer');
exports.$header = RawComponent_js_1.rawComponent('header');
exports.$h1 = RawComponent_js_1.rawComponent('h1');
exports.$h2 = RawComponent_js_1.rawComponent('h2');
exports.$h3 = RawComponent_js_1.rawComponent('h3');
exports.$h4 = RawComponent_js_1.rawComponent('h4');
exports.$h5 = RawComponent_js_1.rawComponent('h5');
exports.$h6 = RawComponent_js_1.rawComponent('h6');
exports.$hgroup = RawComponent_js_1.rawComponent('hgroup');
exports.$main = RawComponent_js_1.rawComponent('main');
exports.$nav = RawComponent_js_1.rawComponent('nav');
exports.$section = RawComponent_js_1.rawComponent('section');
// Text content
exports.$blockquote = RawComponent_js_1.rawComponent('blockquote');
exports.$dd = RawComponent_js_1.rawComponent('dd');
exports.$div = RawComponent_js_1.rawComponent('div');
exports.$dl = RawComponent_js_1.rawComponent('dl');
exports.$dt = RawComponent_js_1.rawComponent('dt');
exports.$figcaption = RawComponent_js_1.rawComponent('figcaption');
exports.$figure = RawComponent_js_1.rawComponent('figure');
exports.$hr = RawComponent_js_1.rawComponent('hr');
exports.$li = RawComponent_js_1.rawComponent('li');
exports.$ol = RawComponent_js_1.rawComponent('ol');
exports.$p = RawComponent_js_1.rawComponent('p');
exports.$pre = RawComponent_js_1.rawComponent('pre');
exports.$ul = RawComponent_js_1.rawComponent('ul');
// Inline text semantics
exports.$a = RawComponent_js_1.rawComponent('a');
exports.$abbr = RawComponent_js_1.rawComponent('abbr');
exports.$b = RawComponent_js_1.rawComponent('b');
exports.$bdi = RawComponent_js_1.rawComponent('bdi');
exports.$bdo = RawComponent_js_1.rawComponent('bdo');
exports.$br = RawComponent_js_1.rawComponent('br');
exports.$cite = RawComponent_js_1.rawComponent('cite');
exports.$code = RawComponent_js_1.rawComponent('code');
exports.$data = RawComponent_js_1.rawComponent('data');
exports.$dfn = RawComponent_js_1.rawComponent('dfn');
exports.$em = RawComponent_js_1.rawComponent('em');
exports.$i = RawComponent_js_1.rawComponent('i');
exports.$kbd = RawComponent_js_1.rawComponent('kbd');
exports.$mark = RawComponent_js_1.rawComponent('mark');
exports.$q = RawComponent_js_1.rawComponent('q');
exports.$rb = RawComponent_js_1.rawComponent('rb');
exports.$rp = RawComponent_js_1.rawComponent('rp');
exports.$rt = RawComponent_js_1.rawComponent('rt');
exports.$rtc = RawComponent_js_1.rawComponent('rtc');
exports.$rbc = RawComponent_js_1.rawComponent('Rbc');
exports.$ruby = RawComponent_js_1.rawComponent('ruby');
exports.$s = RawComponent_js_1.rawComponent('s');
exports.$samp = RawComponent_js_1.rawComponent('samp');
exports.$small = RawComponent_js_1.rawComponent('small');
exports.$span = RawComponent_js_1.rawComponent('span');
exports.$strong = RawComponent_js_1.rawComponent('strong');
exports.$sub = RawComponent_js_1.rawComponent('sub');
exports.$sup = RawComponent_js_1.rawComponent('sup');
exports.$time = RawComponent_js_1.rawComponent('time');
exports.$u = RawComponent_js_1.rawComponent('u');
exports.$variable = RawComponent_js_1.rawComponent('var');
exports.$wbr = RawComponent_js_1.rawComponent('wbr');
// Image and multimedia
exports.$area = RawComponent_js_1.rawComponent('area');
exports.$audio = RawComponent_js_1.rawComponent('audio');
exports.$img = RawComponent_js_1.rawComponent('img');
exports.$map = RawComponent_js_1.rawComponent('map');
exports.$track = RawComponent_js_1.rawComponent('track');
exports.$video = RawComponent_js_1.rawComponent('video');
// Embedded content
exports.$embed = RawComponent_js_1.rawComponent('embed');
exports.$iframe = RawComponent_js_1.rawComponent('iframe');
exports.$object = RawComponent_js_1.rawComponent('object');
exports.$param = RawComponent_js_1.rawComponent('param');
exports.$picture = RawComponent_js_1.rawComponent('picture');
exports.$source = RawComponent_js_1.rawComponent('source');
// Scripting
exports.$canvas = RawComponent_js_1.rawComponent('canvas');
exports.$noscript = RawComponent_js_1.rawComponent('noscript');
exports.$script = RawComponent_js_1.rawComponent('script');
// Demarcating edits
exports.$del = RawComponent_js_1.rawComponent('del');
exports.$ins = RawComponent_js_1.rawComponent('ins');
// Table content
exports.$caption = RawComponent_js_1.rawComponent('caption');
exports.$col = RawComponent_js_1.rawComponent('col');
exports.$colgroup = RawComponent_js_1.rawComponent('colgroup');
exports.$table = RawComponent_js_1.rawComponent('table');
exports.$tbody = RawComponent_js_1.rawComponent('tbody');
exports.$td = RawComponent_js_1.rawComponent('td');
exports.$tfoot = RawComponent_js_1.rawComponent('tfoot');
exports.$th = RawComponent_js_1.rawComponent('th');
exports.$thead = RawComponent_js_1.rawComponent('thead');
exports.$tr = RawComponent_js_1.rawComponent('tr');
// Forms
exports.$button = RawComponent_js_1.rawComponent('button');
exports.$datalist = RawComponent_js_1.rawComponent('datalist');
exports.$fieldset = RawComponent_js_1.rawComponent('fieldset');
exports.$form = RawComponent_js_1.rawComponent('form');
exports.$input = RawComponent_js_1.rawComponent('input');
exports.$label = RawComponent_js_1.rawComponent('label');
exports.$legend = RawComponent_js_1.rawComponent('legend');
exports.$meter = RawComponent_js_1.rawComponent('meter');
exports.$optgroup = RawComponent_js_1.rawComponent('optgroup');
exports.$option = RawComponent_js_1.rawComponent('option');
exports.$output = RawComponent_js_1.rawComponent('output');
exports.$progress = RawComponent_js_1.rawComponent('progress');
exports.$select = RawComponent_js_1.rawComponent('select');
exports.$textarea = RawComponent_js_1.rawComponent('textarea');
// Interactive elements
exports.$details = RawComponent_js_1.rawComponent('details');
exports.$dialog = RawComponent_js_1.rawComponent('dialog');
exports.$menu = RawComponent_js_1.rawComponent('menu');
exports.$summary = RawComponent_js_1.rawComponent('summary');
// Web Components
exports.$slot = RawComponent_js_1.rawComponent('slot');
exports.$template = RawComponent_js_1.rawComponent('template');
//# sourceMappingURL=htmlComponent.js.map