import {rawComponent} from '../core/RawComponent.js'

// Document metadata
export const Link = (...args) => rawComponent('link')(...args)
export const Style = (...args) => rawComponent('style')(...args)

// Content sectioning
export const Address = (...args) => rawComponent('address')(...args)
export const Article = (...args) => rawComponent('article')(...args)
export const Aside = (...args) => rawComponent('aside')(...args)
export const Footer = (...args) => rawComponent('footer')(...args)
export const Header = (...args) => rawComponent('header')(...args)
export const H1 = (...args) => rawComponent('h1')(...args)
export const H2 = (...args) => rawComponent('h2')(...args)
export const H3 = (...args) => rawComponent('h3')(...args)
export const H4 = (...args) => rawComponent('h4')(...args)
export const H5 = (...args) => rawComponent('h5')(...args)
export const H6 = (...args) => rawComponent('h6')(...args)
export const Hgroup = (...args) => rawComponent('hgroup')(...args)
export const Main = (...args) => rawComponent('main')(...args)
export const Nav = (...args) => rawComponent('nav')(...args)
export const Section = (...args) => rawComponent('section')(...args)

// Text content
export const Blockquote = (...args) => rawComponent('blockquote')(...args)
export const Dd = (...args) => rawComponent('dd')(...args)
export const Div = (...args) => rawComponent('div')(...args)
export const Dl = (...args) => rawComponent('dl')(...args)
export const Dt = (...args) => rawComponent('dt')(...args)
export const Figcaption = (...args) => rawComponent('figcaption')(...args)
export const Figure = (...args) => rawComponent('figure')(...args)
export const Hr = (...args) => rawComponent('hr')(...args)
export const Li = (...args) => rawComponent('li')(...args)
export const Ol = (...args) => rawComponent('ol')(...args)
export const P = (...args) => rawComponent('p')(...args)
export const Pre = (...args) => rawComponent('pre')(...args)
export const Ul = (...args) => rawComponent('ul')(...args)

// Inline text semantics
export const A = (...args) => rawComponent('a')(...args)
export const Abbr = (...args) => rawComponent('abbr')(...args)
export const B = (...args) => rawComponent('b')(...args)
export const Bdi = (...args) => rawComponent('bdi')(...args)
export const Bdo = (...args) => rawComponent('bdo')(...args)
export const Br = (...args) => rawComponent('br')(...args)
export const Cite = (...args) => rawComponent('cite')(...args)
export const Code = (...args) => rawComponent('code')(...args)
export const Data = (...args) => rawComponent('data')(...args)
export const Dfn = (...args) => rawComponent('dfn')(...args)
export const Em = (...args) => rawComponent('em')(...args)
export const I = (...args) => rawComponent('i')(...args)
export const Kbd = (...args) => rawComponent('kbd')(...args)
export const Mark = (...args) => rawComponent('mark')(...args)
export const Q = (...args) => rawComponent('q')(...args)
export const Rb = (...args) => rawComponent('rb')(...args)
export const Rp = (...args) => rawComponent('rp')(...args)
export const Rt = (...args) => rawComponent('rt')(...args)
export const Rtc = (...args) => rawComponent('rtc')(...args)
export const Rbc = (...args) => rawComponent('Rbc')(...args)
export const Ruby = (...args) => rawComponent('ruby')(...args)
export const S = (...args) => rawComponent('s')(...args)
export const Samp = (...args) => rawComponent('samp')(...args)
export const Small = (...args) => rawComponent('small')(...args)
export const Span = (...args) => rawComponent('span')(...args)
export const Strong = (...args) => rawComponent('strong')(...args)
export const Sub = (...args) => rawComponent('sub')(...args)
export const Sup = (...args) => rawComponent('sup')(...args)
export const Time = (...args) => rawComponent('time')(...args)
export const U = (...args) => rawComponent('u')(...args)
export const Variable = (...args) => rawComponent('var')(...args)
export const Wbr = (...args) => rawComponent('wbr')(...args)

// Image and multimedia
export const Area = (...args) => rawComponent('area')(...args)
export const Audio = (...args) => rawComponent('audio')(...args)
export const Img = (...args) => rawComponent('img')(...args)
export const Map = (...args) => rawComponent('map')(...args)
export const Track = (...args) => rawComponent('track')(...args)
export const Video = (...args) => rawComponent('video')(...args)

// Embedded content
export const Embed = (...args) => rawComponent('embed')(...args)
export const Iframe = (...args) => rawComponent('iframe')(...args)
export const Object = (...args) => rawComponent('object')(...args)
export const Param = (...args) => rawComponent('param')(...args)
export const Picture = (...args) => rawComponent('picture')(...args)
export const Source = (...args) => rawComponent('source')(...args)

// Scripting
export const Canvas = (...args) => rawComponent('canvas')(...args)
export const Noscript = (...args) => rawComponent('noscript')(...args)
export const Script = (...args) => rawComponent('script')(...args)

// Demarcating edits
export const Del = (...args) => rawComponent('del')(...args)
export const Ins = (...args) => rawComponent('ins')(...args)

// Table content
export const Caption = (...args) => rawComponent('caption')(...args)
export const Col = (...args) => rawComponent('col')(...args)
export const Colgroup = (...args) => rawComponent('colgroup')(...args)
export const Table = (...args) => rawComponent('table')(...args)
export const Tbody = (...args) => rawComponent('tbody')(...args)
export const Td = (...args) => rawComponent('td')(...args)
export const Tfoot = (...args) => rawComponent('tfoot')(...args)
export const Th = (...args) => rawComponent('th')(...args)
export const Thead = (...args) => rawComponent('thead')(...args)
export const Tr = (...args) => rawComponent('tr')(...args)

// Forms
export const Button = (...args) => rawComponent('button')(...args)
export const Datalist = (...args) => rawComponent('datalist')(...args)
export const Fieldset = (...args) => rawComponent('fieldset')(...args)
export const Form = (...args) => rawComponent('form')(...args)
export const Input = (...args) => rawComponent('input')(...args)
export const Label = (...args) => rawComponent('label')(...args)
export const Legend = (...args) => rawComponent('legend')(...args)
export const Meter = (...args) => rawComponent('meter')(...args)
export const Optgroup = (...args) => rawComponent('optgroup')(...args)
export const Option = (...args) => rawComponent('option')(...args)
export const Output = (...args) => rawComponent('output')(...args)
export const Progress = (...args) => rawComponent('progress')(...args)
export const Select = (...args) => rawComponent('select')(...args)
export const Textarea = (...args) => rawComponent('textarea')(...args)

// Interactive elements
export const Details = (...args) => rawComponent('details')(...args)
export const Dialog = (...args) => rawComponent('dialog')(...args)
export const Menu = (...args) => rawComponent('menu')(...args)
export const Summary = (...args) => rawComponent('summary')(...args)

// Web Components
export const Slot = (...args) => rawComponent('slot')(...args)
export const Template = (...args) => rawComponent('template')(...args)
