import {rawComponent} from '../core/RawComponent'

// Structural Tags
export const A = rawComponent('a')
export const Article = rawComponent('article')
export const Aside = rawComponent('aside')
export const Body = rawComponent('body')
export const Br = rawComponent('br')
export const Details = rawComponent('details')
export const Div = rawComponent('div')
export const H1 = rawComponent('h1')
export const Head = rawComponent('head')
export const Header = rawComponent('header')
export const Hgroup = rawComponent('hgroup')
export const Hr = rawComponent('hr')
export const Html = rawComponent('html')
export const Footer = rawComponent('footer')
export const Nav = rawComponent('nav')
export const P = rawComponent('p')
export const Section = rawComponent('section')
export const Span = rawComponent('span')
export const Summary = rawComponent('summary')

// Metadata Tags
export const Base = rawComponent('base')
export const Link = rawComponent('link')
export const Meta = rawComponent('meta')
export const Style = rawComponent('style')
export const Title = rawComponent('title')

// Form Tags
export const Button = rawComponent('button')
export const Datalist = rawComponent('datalist')
export const Fieldset = rawComponent('fieldset')
export const Form = rawComponent('form')
export const Input = rawComponent('input')
export const Keygen = rawComponent('keygen')
export const Label = rawComponent('label')
export const Legend = rawComponent('legend')
export const Meter = rawComponent('meter')
export const Optgroup = rawComponent('optgroup')
export const Option = rawComponent('option')
export const Select = rawComponent('select')
export const Textarea = rawComponent('textarea')

// Formatting Tags
export const Abbr = rawComponent('abbr')
export const Acronym = rawComponent('acronym')
export const Address = rawComponent('address')
export const B = rawComponent('b')
export const Bdi = rawComponent('bdi')
export const Bdo = rawComponent('bdo')
export const Big = rawComponent('big')
export const Blockquote = rawComponent('blockquote')
export const Cite = rawComponent('cite')
export const Code = rawComponent('code')
export const Del = rawComponent('del')
export const Dfn = rawComponent('dfn')
export const Em = rawComponent('em')
export const I = rawComponent('i')
export const Ins = rawComponent('ins')
export const Kbd = rawComponent('kbd')
export const Mark = rawComponent('mark')
export const Output = rawComponent('output')
export const Pre = rawComponent('pre')
export const Progress = rawComponent('progress')
export const Q = rawComponent('q')
export const Rp = rawComponent('rp')
export const Rt = rawComponent('rt')
export const Ruby = rawComponent('ruby')
export const Samp = rawComponent('samp')
export const Small = rawComponent('small')
export const Strong = rawComponent('strong')
export const Sub = rawComponent('sub')
export const Sup = rawComponent('sup')
export const Tt = rawComponent('tt')
export const Var = rawComponent('var')
export const Wbr = rawComponent('wbr')

// List Tags
export const Dd = rawComponent('dd')
export const Dl = rawComponent('dl')
export const Dt = rawComponent('dt')
export const Li = rawComponent('li')
export const Ol = rawComponent('ol')
export const Menu = rawComponent('menu')
export const Ul = rawComponent('ul')

// Table Tags
export const Caption = rawComponent('caption')
export const Col = rawComponent('col')
export const Colgroup = rawComponent('colgroup')
export const Table = rawComponent('table')
export const Tbody = rawComponent('tbody')
export const Td = rawComponent('td')
export const Tfoot = rawComponent('tfoot')
export const Thead = rawComponent('thead')
export const Th = rawComponent('th')
export const Tr = rawComponent('tr')

// Scripting Tags
export const Noscript = rawComponent('noscript')
export const Script = rawComponent('script')

// Embedded Content Tags
export const Area = rawComponent('area')
export const Audio = rawComponent('audio')
export const Canvas = rawComponent('canvas')
export const Embed = rawComponent('embed')
export const Figcaption = rawComponent('figcaption')
export const Figure = rawComponent('figure')
export const Frame = rawComponent('frame')
export const Frameset = rawComponent('frameset')
export const Iframe = rawComponent('iframe')
export const Img = rawComponent('img')
export const Map = rawComponent('map')
export const Noframes = rawComponent('noframes')
export const Object = rawComponent('object')
export const Param = rawComponent('param')
export const Source = rawComponent('source')
export const Time = rawComponent('time')
export const Video = rawComponent('video')
