import {rawComponent} from '../core/RawComponent.js'

// Document metadata
export const link = rawComponent('link')
export const style = rawComponent('style')

// Content sectioning
export const address = rawComponent('address')
export const article = rawComponent('article')
export const aside = rawComponent('aside')
export const footer = rawComponent('footer')
export const header = rawComponent('header')
export const h1 = rawComponent('h1')
export const h2 = rawComponent('h2')
export const h3 = rawComponent('h3')
export const h4 = rawComponent('h4')
export const h5 = rawComponent('h5')
export const h6 = rawComponent('h6')
export const hgroup = rawComponent('hgroup')
export const main = rawComponent('main')
export const nav = rawComponent('nav')
export const section = rawComponent('section')

// Text content
export const blockquote = rawComponent('blockquote')
export const dd = rawComponent('dd')
export const div = rawComponent('div')
export const dl = rawComponent('dl')
export const dt = rawComponent('dt')
export const figcaption = rawComponent('figcaption')
export const figure = rawComponent('figure')
export const hr = rawComponent('hr')
export const li = rawComponent('li')
export const ol = rawComponent('ol')
export const p = rawComponent('p')
export const pre = rawComponent('pre')
export const ul = rawComponent('ul')

// Inline text semantics
export const a = rawComponent('a')
export const abbr = rawComponent('abbr')
export const b = rawComponent('b')
export const bdi = rawComponent('bdi')
export const bdo = rawComponent('bdo')
export const br = rawComponent('br')
export const cite = rawComponent('cite')
export const code = rawComponent('code')
export const data = rawComponent('data')
export const dfn = rawComponent('dfn')
export const em = rawComponent('em')
export const i = rawComponent('i')
export const kbd = rawComponent('kbd')
export const mark = rawComponent('mark')
export const q = rawComponent('q')
export const rb = rawComponent('rb')
export const rp = rawComponent('rp')
export const rt = rawComponent('rt')
export const rtc = rawComponent('rtc')
export const rbc = rawComponent('Rbc')
export const ruby = rawComponent('ruby')
export const s = rawComponent('s')
export const samp = rawComponent('samp')
export const small = rawComponent('small')
export const span = rawComponent('span')
export const strong = rawComponent('strong')
export const sub = rawComponent('sub')
export const sup = rawComponent('sup')
export const time = rawComponent('time')
export const u = rawComponent('u')
export const variable = rawComponent('var')
export const wbr = rawComponent('wbr')

// Image and multimedia
export const area = rawComponent('area')
export const audio = rawComponent('audio')
export const img = rawComponent('img')
export const map = rawComponent('map')
export const track = rawComponent('track')
export const video = rawComponent('video')

// Embedded content
export const embed = rawComponent('embed')
export const iframe = rawComponent('iframe')
export const object = rawComponent('object')
export const param = rawComponent('param')
export const picture = rawComponent('picture')
export const source = rawComponent('source')

// Scripting
export const canvas = rawComponent('canvas')
export const noscript = rawComponent('noscript')
export const script = rawComponent('script')

// Demarcating edits
export const del = rawComponent('del')
export const ins = rawComponent('ins')

// Table content
export const caption = rawComponent('caption')
export const col = rawComponent('col')
export const colgroup = rawComponent('colgroup')
export const table = rawComponent('table')
export const tbody = rawComponent('tbody')
export const td = rawComponent('td')
export const tfoot = rawComponent('tfoot')
export const th = rawComponent('th')
export const thead = rawComponent('thead')
export const tr = rawComponent('tr')

// Forms
export const button = rawComponent('button')
export const datalist = rawComponent('datalist')
export const fieldset = rawComponent('fieldset')
export const form = rawComponent('form')
export const input = rawComponent('input')
export const label = rawComponent('label')
export const legend = rawComponent('legend')
export const meter = rawComponent('meter')
export const optgroup = rawComponent('optgroup')
export const option = rawComponent('option')
export const output = rawComponent('output')
export const progress = rawComponent('progress')
export const select = rawComponent('select')
export const textarea = rawComponent('textarea')

// Interactive elements
export const details = rawComponent('details')
export const dialog = rawComponent('dialog')
export const menu = rawComponent('menu')
export const summary = rawComponent('summary')

// Web Components
export const slot = rawComponent('slot')
export const template = rawComponent('template')
